### ISSUE TITLE
Could not find the CLEyeMulticam.dll

### ISSUE THREAD

**Issue by yinchuangsum** [CertifaiAI/CertifAI-Knowledge-Base#42]
2021-03-16 13:20:25 INFO  AvocadoBananaDetector_YOLOv2:386 -  Completed epoch 40 
Model saved.
RealSense devices found: 0
(1) Could not find the CLEyeMulticam.dll
(2) Could not find the CLEyeMulticam.dll

how can i solve this CLEyeMulticam.dll problem

**Comment by codenamewei** [comment]
@YCCertifai do add comments on why the issue is closed.

**Comment by yinchuangsum** [comment]
This is not really an issue..
It is just a log coming from [javacv](https://github.com/bytedeco/javacv/blob/master/src/main/java/cl/eye/CLCamera.java#L81) ..
as long as webcam shows up, that's not a big deal.
